export default {
  INIT: 'INIT',
  IMPORTING_GENOME: 'IMPORTING_GENOME',
  EXPORTING_GENOME: 'EXPORTING_GENOME',
  HUMAN: 'HUMAN',
  GAME_OVER: 'GAME_OVER',
  TRAINING: 'TRAINING',
  TRAINING_OVER: 'TRAINING_OVER',
  REPLAY: 'REPLAY',
  REPLAY_DONE: 'REPLAY_DONE',
};
